title: Répertoire International des Sources Musicales
email: contact@rism.info
description: >- # this means to ignore newlines
  The organization, founded in Paris in 1952, is the largest and only global
  operation that documents written musical sources.
  RISM records what exists and where it can be found.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rism.info" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RISM_Music

languages: ["en", "de", "fr"]
default_lang: "en"
exclude_from_localization: ["assets", "javascript", "images", "css", "README.md"]
parallel_localization: false
lang_from_path: false
